services:
  - type: web
    name: agenda-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: data-volume
      mountPath: /data
      sizeGB: 1
